### PR TITLE
Noise Subsystem

### PR DESCRIPTION
**Pull request by eyedeekay**
This is a big one, and there's a lot that comes with it, so we're going to put it in a PR here so we have a convenient way to view everything that is going on. This contains, more-or-less, all the work needed to implement the Noise subsystem, including updates and implementations of cryptographic primitives and functions and our first glimpses of a working transport implementation. We need to take some time to go back over everything we've done here, list it, ensure it's documented, ensure we think it can do what we need, and get it merged. Let's target having it locked in by next Friday, earlier if we can.

### CODE REVIEW

**Comment by eyedeekay** [comment]
Abbreviated summary of changes in `lib/transport/noise`:

```
- Replace simple flynn/noise wrapper with general transport layer
- Add NoiseSession and NoiseTransport structures for better session management
- Add encryption/decryption packet testing
- Improve handshake handling with separate initiator/responder paths
- Add protocol-specific constants and improved type definitions
- Add comprehensive offline encryption/decryption tests
- Add basic obfuscation testing
```

Anything to add to that @hkh4n ? Specifically I'm looking at general changes in `lib/transport/noise` which is where the bulk of the most important changes will occur, we'll look at crypto later.

**Comment by hkh4n** [comment]
@eyedeekay 


For `lib/transport/noise`: ~~The functions `encryptPacket()` and `decryptPacket()` can be replaced (with the same name) with `encryptPacketDeux()` and `decryptPacketDeux()` since the only usages for those prior functions are in `TestEncryptDecryptPacketOffline(t *testing.T)` and `func TestEncryptDecryptPacketObfsOffline(t *testing.T)` which can be deprecated as it was only there for demonstration purposes.~~ (I had it the other way around, and these will be moved as `testEncryptPacket()` and `testDecryptPacket()`.)

 As you mentioned, documentation needs to be done as well.

For things not related to `lib/transport/noise`:  There are still artifacts of info logs while logging only should implement debug, warn and error. And we should see if there can be additional polishing on the config as you mentioned in https://github.com/go-i2p/go-i2p/pull/18#issuecomment-2448522151.

Edit: `log.Fatalf` in `InitConfig` as it may be necessary as `func OnInitialize()` only accepts `...func()` as an arg so we cannot inject a function that returns an error. It may be possible to work around it.

**Comment by hkh4n** [comment]
Got polishes done here: https://github.com/go-i2p/go-i2p/pull/20

**Comment by eyedeekay** [comment]
Merge the polishes, we've got `go.mod` and `go.sum` conflicts with master because I just merged the sntp-experimental branch, but what we'll do is we'll resolve the merge conflict in whatever way is most convenient and re-generate the `go.mod` and `go.sum` files. Polishes have it looking pretty good, I'm thinking we might be ready ahead of schedule.

**Comment by eyedeekay** [comment]
Merged the polishes, we've got `go.mod` and `go.sum` conflicts with master because I just merged the sntp-experimental branch, but what we'll do is we'll resolve the merge conflict in whatever way is most convenient and re-generate the `go.mod` and `go.sum` files. Polishes have it looking pretty good, I'm thinking we might be ready ahead of schedule.

I think we'll just figure out the rest when we do NTCP2.

**Pull request merged**
