### PR TITLE
SU3

### PR DESCRIPTION
**Pull request by apeace**
I've done a significant refactor of SU3 file parsing.

## Testing

```
go test ./lib/su3/...
```

## Example Usage

Getting the content as `[]byte` from an HTTP body:

```go
// Let's say we are reading an SU3 file from an HTTP body, which is an io.Reader.
su3File, err := su3.Read(body)
if err != nil {
    // Handle error.
}
// Look up this signer's key.
key := somehow_lookup_the_key(su3File.SignerID)
// Read the content.
contentReader := su3File.Content(key)
bytes, err := ioutil.ReadAll(contentReader)
if errors.Is(err, su3.ErrInvalidSignature) {
    // The signature is invalid, OR a nil key was provided.
} else if err != nil {
    // Handle error.
}
```

If you already have `[]byte` as opposed to an `io.Reader`, you can wrap it like this:

```go
mySU3FileBytes := []byte{0x00, 0x01, 0x02, 0x03}
su3File, err := su3.Read(bytes.NewReader(mySU3FileBytes))
```

One of the advantages of this library's design is that you can avoid buffering the file contents in memory. Here's how you would stream from an HTTP body directly to disk:

```go
su3File, err := su3.Read(body)
if err != nil {
    // Handle error.
}
// Look up this signer's key.
key := somehow_lookup_the_key(su3File.SignerID)
// Stream directly to disk.
f, err := os.Create("my_file.txt")
if err != nil {
    // Handle error.
}
_, err := io.Copy(f, su3File.Content(key))
if errors.Is(err, su3.ErrInvalidSignature) {
    // The signature is invalid, OR a nil key was provided.
    // Don't trust the file, delete it!
} else if err != nil {
    // Handle error.
}
```

## Caveats

I am using Go 1.18 on my local, so I have a modified `go.mod` and `go.sum` that I have not checked in. I don't think that should be an issue, but if you run into any weird errors that's probably the issue. Let me know if that happens, and I can downgrade to Go 1.16 and get all tests passing.

**Help Requested**. Right now the tests with `reseed-i2pgit.su3` are not passing, so I've marked them as skipped. Is it possible that the key I'm using (`hankhill19580_at_gmail.com.crt`) is not the one used to sign that reseed file?

## Changes

Here is a summary of the changes I made.

### Moved to `lib/`

I think SU3 files are about more than just config, so `lib/` seems like a better place for this package. It's nice to have it be standalone.

### Utilizing `io.Reader`

The previous design worked with `[]byte`, which is fine, except if you ever work with a large SU3 file. Using `io.Reader` allows us to stream the contents of SU3 files from a network request directly to disk, without buffering the whole file in memory.

### Verifying signatures

The old su3 package did not verify signatures. One could argue that this should be the responsibility of a different package, but I think it is best for the su3 package to do it. The reason is, I want to avoid a situation where a developer forgets to verify the signature, and ends up trusting an improperly-signed file. The way I have it implemented, you have to go out of your way to ignore `ErrInvalidSignature` if you want to use an untrusted file.

### Improve tests

Several improvements were made to the tests.

The new tests are table-driven. This makes it cleaner and more convenient to add lots of test cases.

We also test the end-to-end functionality of parsing an SU3 file. The previous tests focused on testing internal functions, such as `checkMagicBytes` or `getSignatureType`. This makes the tests brittle, because if we ever wanted to change the implementation, we would need to update the tests. By testing end-to-end, we could change the implementation completely without modifying the tests. We could rewrite it to call into a C library, and the tests would remain exactly the same.

Finally, the new tests not only test with fake data derived for testing purposes only, but also test against a real SU3 file found in the wild. It's important to test against data that's as real as possible.

### Package documentation

I added some package documentation. It's not great, but it's a start!

## Future work

If we move forward with this refactored version, these are the things I'd like to work on next:

- [ ] **Testing more file types.** I would like to test a real-world SU3 file for every file type. Router update, plugin, etc. If you could point me to some files, that would be helpful!
- [ ] **SU3 writing.** It would be neat to have functionality for writing SU3 files. I'd like to implement a command-line tool for generating SU3s, as a demonstration of this cabability.

EDIT: I added signature validation to this PR.

### CODE REVIEW

**Comment by eyedeekay** [comment]
Reviewed and approved in concept, but if you're going to name variables in tests something like `apeaceKey` then at some point I'm probably going to ask you to make that key permanent and not generate it inside the test. Not a big deal for now though, we can do that in the future.

I'll help you track down all the other required types of `su3` files for testing with your implementation, adding them below as I go

 - plugin: https://github.com/eyedeekay/blizzard/releases has su3's of a simple plugin
 - update type EXE: https://github.com/eyedeekay/i2p.firefox/releases/tag/2021-su3

Not sure what's wrong with the reseed verification process, I'm quite sure that is the correct key for reseed.i2pgit.org. I almost understand why it's not verifying, will get back to you on it soon.

You may also want to look at https://github.com/eyedeekay/reseed-tools for hints, it contains a fairly extensive set of su3 tools as well which will be good examples.

I'll take care of the Go modules update on my side. Thanks again for your contributions so far!

**Comment by apeace** [comment]
Thanks so much, all those SU3s will be helpful for tests!

If you're sure it's the right key, then I must have implemented signature verification wrong. If you have any ideas on where I went wrong that would be a huge help. I will also take a look at `reseed-tools` for hints.

That is a good point on the naming. Perhaps I should rename everything in that section to `testKey`, `testContent`, etc. For those tests I want to keep them generated so that a fake/unused key doesn't get advertised to the world (like you were pointing out).

**Comment by apeace** [comment]
@eyedeekay I refactored the test data, so it is much cleaner now. It uses `alice` and `bob` so that it is more obvious that it's fake :)

I still need to look into those skipped tests and figure out where I've gone wrong on signature validation. Will do that soon.

**Comment by eyedeekay** [comment]
Thanks @apeace I updated the modules and refactored a few tests on the master, should not interfere with your changes, feel free to pull them into your branch if you want to switch to 1.18

**Comment by apeace** [comment]
@eyedeekay Nice! I just rebased.

**Comment by apeace** [comment]
@eyedeekay I took a look at `reseed-tools` and I was able to distill the signature verification process down to this:

https://github.com/apeace/go-i2p/blob/136133e6436ada4e093e9249a6313508e33dccb1/lib/su3/su3_test.go#L70-L96

I extracted the content and the signature of two SU3 files, and those two tests are just verifying the signature. The tests don't pass right now.

I'm thinking that I may not have extracted the content/signature correctly, because I can't see any difference in the signature-verification code between here and `reseed-tools`. But `reseed-i2pgit-content.zip` is a valid zip file containing router infos, and the signature files are both exactly 512 bytes.

So, at the moment I am stuck. I will get back to it eventually, though, if you don't have time to take a look.

Are you able to run `reseed-tools verify reseed-i2pgit.su3`? I am getting some errors when trying to build `reseed-tools`. My next step will be trying to get past those errors so that I can run `reseed-tools verify` as a sanity check.

**Comment by apeace** [comment]
@eyedeekay I figured it out. I was only hashing the "file contents", *not the entire SU3 file* up to the end of the file contents. As per the spec `"Signature: Length is specified in header at bytes 10-11, covers everything starting at byte 0"`. DUHHHH! 😛 

Fixed that, and it now works! `reseed-tools` was instrumental in helping me figure that out!

So, I'd like to request your final review on this PR.

I would like to send the next steps in a follow-up PR:
 - Implementing the rest of the signature algorithms. Right now only RSA is included, but the rest should be trivial to add.
 - Tracking down more SU3 files in the wild. I'd like to have a test for each and every file type!
 - SU3 writing.

**Comment by eyedeekay** [comment]
Awesome, I approve of that plan and have reviewed, will merge shortly.

**Pull request merged**
