### PR TITLE
Add signature tests

### PR DESCRIPTION
**Pull request by satk0**
`ReadSignature` function uses only 2 signature types even though there are more specified signatures in the file. Can I implement it and test it too?

### CODE REVIEW

**Comment by eyedeekay** [comment]
Sure @satk0 feel free to implement it and test it.

**Comment by eyedeekay** [comment]
We merged #26 today, if possible, please resolve any emerging merge conflicts when you implement other sigtypes

**Comment by hkh4n** [comment]
Good work as always @satk0, be sure if you can to integrate your tests into the appropriate .mk file located in doc/tests and add the test to the matrix in .github/workflows/tests.yml :)

**Comment by eyedeekay** [comment]
Good point @hkh4n

**Comment by satk0** [comment]
@eyedeekay @hkh4n Yeah, sure, will do that. Great that you managed to merge it. I can see that this project is accelerating, great job !

Btw, sorry for the late response. I was pretty busy cuz of Uni stuff, meh. By the end of this week I hope that I could find some time to finish this PR :rocket:

**Comment by satk0** [comment]
Hey, I rebased to master and added more certificates but it seems like `test-noise-transport-all` test is failing, should I fix that?

**Comment by satk0** [comment]
`test-noise-transport-all` sometimes passes, sometimes not, lool

@eyedeekay @hkh4n I think I am done, could you guys plz chck?

**Comment by eyedeekay** [comment]
On it, will have feedback in a couple hours

**Comment by eyedeekay** [comment]
Yeah TBH looks good, I don't think you need to change anything that's here and the tests look adequate. Thanks for the PR, looking forward to working more with you :)

**Comment by satk0** [comment]
Thanks for merging!

**Pull request merged**
