### PR TITLE
Fix key certificate tests

### PR DESCRIPTION
**Pull request by satk0**
That's all to get the `key_certificate` tests working, should I also implement the renames and rewrites that PR #5 was intended to do?

### CODE REVIEW

**Comment by satk0** [comment]
Okey, I will add them then, and also add test to check the `spk` value

**Comment by hkh4n** [comment]
> Okey, I will add them then, and also add test to check the `spk` value
@satk0 

My apologies, I just gave a thumbs up because I appreciate the work you're doing. That's my bad on communication sorry haha.

We're actually in the midst of something that is colliding with the good work you're doing. https://github.com/go-i2p/go-i2p/pull/23/commits/98d05e27c8c3cd1a4cde1b6899d131781b4f216b#diff-0ed98cca3160278053da430fead068f11c258a6599685bb6390737b35a4cda0e

We're still working on it, but as of now it's in a bit of a flux. But you can try and @eyedeekay can review the changes and see if it can merged in, no worries.

**Comment by satk0** [comment]
Oooh allright, hah, thanks for all the good words 💪 I am just so excited about this project that I can't wait to do anything haha

I see, I will just leave all the refactoring to you, you are far more experienced.

I can add `spk` value checking in the test, that could help in refactoring it I think.

If you don't mind, I can make more PRs fixing or implementing tests, if that could help ;)

**Comment by eyedeekay** [comment]
Let's go ahead and merge this soon, we can resolve the conflict before we merge the routerinfo branch

**Comment by eyedeekay** [comment]
Let's not rename or rewrite more things just yet though, put that in another branch and make a new PR for it.

**Comment by satk0** [comment]
Thanks for merging @eyedeekay, I will add more PRs with tests fixes soon

**Pull request merged**
