### PR TITLE
Refactoring tests

### PR DESCRIPTION
**Pull request by hkh4n**
Many tests are currently broken, in order to have a stable foundation to work on; we need to ensure that all tests pass.

### CODE REVIEW

**Comment by hkh4n** [comment]
Note to self: made a mistake in https://github.com/go-i2p/go-i2p/commit/3acff32f17124adc466e611768bebdd66508f4eb that is causing some tests to fail.

**Comment by satk0** [comment]
Man, you are a cyborg

**Comment by eyedeekay** [comment]
Doing some pre-review here since we're going to have another big merge ahead of us here:

ACK to String fixes as-is
ACK to uniform errors, feel free to create/replace existing errors with uniform errors in other areas as you go, it'll make things easier to review and keep things from breaking in the future
ACK to Mapping fixes as-is

From there things get a little deeper, I'll reply again soon as I look closer at the crypto stuff and the readers/constructors

**Comment by eyedeekay** [comment]
Just ran the test suite after going over the changes, impressive work so far :)

**Comment by eyedeekay** [comment]
There is a test that fails 50% of the time in Mapping, `TestFullGoMapToMappingProducesCorrectMapping`. It is failing but the I2P Mapping code is correct. The reason is that the go map is unordered, and the I2P Mapping is ordered. To fix the test you'll have to rewrite it to check value equivalency key by key instead of over the whole map all at once, look up the key in map A, look up the key in map B, then compare the values. Do this for each k/v pair.

**Comment by hkh4n** [comment]
> There is a test that fails 50% of the time in Mapping, `TestFullGoMapToMappingProducesCorrectMapping`. It is failing but the I2P Mapping code is correct. The reason is that the go map is unordered, and the I2P Mapping is ordered. To fix the test you'll have to rewrite it to check value equivalency key by key instead of over the whole map all at once, look up the key in map A, look up the key in map B, then compare the values. Do this for each k/v pair.

Corrected in https://github.com/go-i2p/go-i2p/pull/26/commits/c68acf848e6557823e1df26979c07fc70b72b780

**Comment by satk0** [comment]
Great job!

**Comment by eyedeekay** [comment]
@hkh4n @satk0 OK I think we're at merge time or close to it. I think this and #30 might offer a bit of an adventure to get everything merged into the master branch without conflicts but I think I'll get it done today.

**Pull request merged**
